[package]
name = "oid4vci"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
keywords = ["oid4vc", "openid4vc", "oid4vci", "OpenID Connect"]
license.workspace = true
repository.workspace = true
