[package]
name = "dif-presentation-exchange"
version = "0.1.0"
edition = "2021"
homepage.workspace = true
keywords = ["oid4vc", "dif-presentation-exchange", "Decentralized Identity Foundation", "DIF", "OpenID"]
license.workspace = true
repository.workspace = true
